### ISSUE TITLE
Requires TFA code for each authorization

### ISSUE THREAD

**Issue by rostikowb** [andrewstoliarov/apple-search-ads#4]
Hi, can you help me? Every time the session expires, you have to enter the TFA code, can you tell me how to make the device be remembered, like in a browser?

**Comment by andrewstoliarov** [comment]
@rostikowb Do you save cookies for the next authorization ?

**Comment by rostikowb** [comment]
> @rostikowbЧи зберігаєте ви файли cookie та xsrfToken для наступної авторизації?

Yes, but cookies are enough for a day, then you need to log in again using the TFA code.

**Comment by andrewstoliarov** [comment]
@rostikowb You need to log in every half hour and re-save cookies and xsrfToken.
