### ISSUE TITLE
2FA Status Code 400

### ISSUE THREAD

**Issue by alpennec** [andrewstoliarov/apple-search-ads#5]
Hello,

I'm trying to get 2FA work but for an unknown reason, the call too https://idmsa.apple.com/appleauth/auth/2sv/trust does not work. I receive a 400 error.

Do you have any idea how to deal with that?

Thanks

**Comment by andrewstoliarov** [comment]
@alpennec Hello.
Before this, do you call 
https://idmsa.apple.com/appleauth/auth/verify/trusteddevice/securitycode
?

**Comment by alpennec** [comment]
Yes I do call this method before. And I get status 200 here.
But when I inspect my auth data from the endpoint https://idmsa.apple.com/appleauth/auth, I notice there are no trustedDevices associated with my account.
This seems strange because I receive the prompt on my iPhone and Mac.

Could this be the reason?

PS: I’m writing a native Swift app, not using your library directly.

￼

**Comment by andrewstoliarov** [comment]
Most likely, you're missing the necessary headers. Try running a test from my library to rule out other possibilities.

**Comment by alpennec** [comment]
Thanks for the help, I'll try to see how I can run your library. I'm not well aware of how to use js unfortunately.

**Comment by andrewstoliarov** [comment]
Previously, it was possible to use users with just a password, but Apple has enforced 2FA (Two-Factor Authentication) for all users.

**Comment by alpennec** [comment]
Ok thanks. But I think there is another way because apps are using this app-specific password.
