### ISSUE TITLE
503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by alpennec** [andrewstoliarov/apple-search-ads#6]
Hello,

I'm trying to run the `node testGetPopularity.js` from the test folder, but I get `503 Service Temporarily Unavailable`.
The Apple Search Ads website is working normally, without any downtime. The Apple status page doesn't report anything.

I think the issue is from the https://idmsa.apple.com/appleauth/auth/signin endpoint.

Have you experienced the same on your side?

Thanks,
Axel

<img width="1563" alt="image" src="https://github.com/user-attachments/assets/231d43cf-1501-4325-8d76-b60ab5da35d7">

**Comment by andrewstoliarov** [comment]
@alpennec Yes, I get this error sometimes. It's necessary to use a retry here.

**Comment by alpennec** [comment]
Ok thanks, I'll try again later. I called the script many times and always get the 503.
Let me know if you test on your side. Thanks.

**Comment by alpennec** [comment]
Xcodes app is having the same problem. They use the same URL to sign in to an Apple account. I opened a ticket on their repository: https://github.com/XcodesOrg/XcodesApp/issues/630

And I guess fastlane should be impacted too (I haven’t checked what URL they use to sign in).

I fear Apple changed something to prevent these sorts of login.
